-- V9__add_user_code_column.sql
-- Add user_code column for human-readable user IDs

-- Add user_code column to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS user_code VARCHAR(50) UNIQUE;

-- Create index for faster lookups
CREATE INDEX IF NOT EXISTS idx_user_code ON users(user_code);

-- Add comment to explain the column
COMMENT ON COLUMN users.user_code IS 'Human-readable user ID generated by egov-idgen service (e.g., USER-2024-000001)';
